# Generated by Django 3.2.5 on 2021-07-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_created',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
